kind: "CDN"
version: "1"
metadata:
  envTypes: ["dev", "stage", "prod"]
data:
  trafficFilters:
    rules:
      # Block client for 5m when it exceeds an average of 100 req/sec to origin on a time window of 10sec
      - name: limit-origin-requests-client-ip
        when:
          reqProperty: tier
          equals: 'publish'
        rateLimit:
          limit: 100
          window: 10
          count: fetches
          penalty: 300
          groupBy:
            - reqProperty: clientIp
        action: log

      # Block client for 5m when it exceeds an average of 500 req/sec on a time window of 10sec
      - name: limit-requests-client-ip
        when:
          reqProperty: tier
          equals: 'publish'
        rateLimit:
          limit: 500
          window: 10
          count: all
          penalty: 300
          groupBy:
            - reqProperty: clientIp
        action: log

      # Block requests coming from OFAC countries
      - name: block-ofac-countries
        when:
          allOf:
            - { reqProperty: tier, in: ["author", "publish"] }
            - reqProperty: clientCountry
              in:
                - SY
                - BY
                - MM
                - KP
                - IQ
                - CD
                - SD
                - IR
                - LR
                - ZW
                - CU
                - CI
        action: log

      # Enable recommended WAF protections (only works if WAF is licensed enabled for your environment)
      - name: block-waf-flags-globally
        when:
          reqProperty: tier
          in: ["author", "publish"]
        action:
          type: log
          wafFlags:
            - TRAVERSAL
            - CMDEXE-NO-BIN
            - XSS
            - LOG4J-JNDI
            - BACKDOOR
            - USERAGENT
            - SQLI
            - SANS
            - TORNODE
            - NOUA
            - SCANNER
            - PRIVATEFILE
            - NULLBYTE

  originSelectors:
    rules:
      - name: route-skipton-eds-demo
        when:
          allOf:
            - reqProperty: tier
              equals: publish
            - reqProperty: domain
              equals: publish-p133255-e1921317.adobeaemcloud.com
            - anyOf:
                - reqProperty: path
                  matches: "^/help-and-support(?:/.*|(?:\\.plain)?\\.html)?$"
                - reqProperty: path
                  matches: "^/(?:nav|footer)(?:\\.plain)?\\.html$"
                - reqProperty: path
                  matches: "^/(?:scripts|styles|fonts|blocks|icons|assets)/.*$"
                - reqProperty: path
                  matches: "^.*/media_.*$"
                - reqProperty: path
                  equals: /favicon.ico
        action:
          type: selectOrigin
          originName: skipton-eds-demo

    origins:
      - name: skipton-eds-demo
        domain: main--skipton-eds-demo--gaurravv.aem.live